name:                status-notifier-item
version:             0.1.0.0
github:              "IvanMalison/status-notifier-item"
license:             BSD3
author:              "Ivan Malison"
maintainer:          "IvanMalison@gmail.com"
copyright:           "2018 Ivan Malison"

extra-source-files:
- README.md
- ChangeLog.md
- xml/*

description: Please see the README on Github at <https://github.com/IvanMalison/status-notifier-item#readme>

library:
  source-dirs: src
  dependencies:
    - base >= 4.7 && < 5
    - bytestring
    - containers
    - dbus > 1.0
    - hslogger
    - filepath
    - mtl
    - template-haskell
    - vector

executables:
  status-notifier-watcher:
    source-dirs: ./watcher
    dependencies:
      - base >= 4.7 && < 5
      - dbus > 1.0
      - status-notifier-item
      - optparse-applicative
    main: Main.hs
  sni-cl-tool:
    source-dirs: ./tool
    dependencies:
      - base >= 4.7 && < 5
      - dbus > 1.0
      - status-notifier-item
      - optparse-applicative
    main: Main.hs
