name:                status-notifier-item-tray
version:             0.1.0.0
github:              "IvanMalison/status-notifier-item-tray"
license:             BSD3
author:              "Ivan Malison"
maintainer:          "IvanMalison@gmail.com"
copyright:           "2018 Ivan Malison"

extra-source-files:
- README.md
- ChangeLog.md

description: Please see the README on Github at <https://github.com/IvanMalison/status-notifier-item-tray#readme>

library:
  source-dirs: src
  dependencies:
    - base >= 4.7 && < 5
    - dbus > 1.0
    - filepath
    - gtk3

executables:
  status-notifier-watcher:
    source-dirs: .
    dependencies:
      - base >= 4.7 && < 5
      - status-notifier-item-tray
    main: WatcherMain.hs
