name:                appindicator-tray
version:             0.1.0.0
github:              "githubuser/appindicator-tray"
license:             BSD3
author:              "Ivan Malison"
maintainer:          "IvanMalison@gmail.com"
copyright:           "2018 Ivan Malison"

extra-source-files:
- README.md
- ChangeLog.md

data-files: xml/*

description:         Please see the README on Github at <https://github.com/IvanMalison/appindicator-tray#readme>

dependencies:
- base >= 4.7 && < 5
- dbus >= 0.10.7 && < 1.0
- filepath
- gtk3

pkg-config-dependencies: [gtk+-3.0]

library:
  source-dirs: src
