resolver: lts-10.7

packages:
- .
- location:
    git: https://github.com/IvanMalison/haskell-dbus
    commit: 5ee47736827f6b499d18167b13ff2fc8b037db96
  extra-dep: true
extra-deps:
  - gtk3-0.14.8
  - gio-0.13.4.1
