resolver: lts-10.7

packages:
- .
- location:
    git: https://github.com/IvanMalison/haskell-dbus
    commit: 92e4c8f0c5ddd45051510d411266f140e9d750e4
  extra-dep: true
extra-deps:
  - gtk3-0.14.8
  - gio-0.13.4.1
